### ISSUE TITLE
有pythno版本吗

### ISSUE THREAD

**Issue by SeekPoint** [Motianshi/all-search#1]

**Comment by Motianshi** [comment]
暂时没有 抱歉



---原始邮件---
发件人: "yk_data"<notifications@github.com&gt;
发送时间: 2020年9月24日(周四) 下午4:52
收件人: "Motianshi/all-search"<all-search@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Motianshi/all-search] 有pythno版本吗 (#1)
